### ISSUE TITLE
Remake scoring

### ISSUE THREAD

**Issue by grmike** [madddmax/jackal#116]
Переделать подсчёт очков для определения конца игры:
- монеты, оставшиеся на людоеде, считать выбывшими из игры
- не заканчивать игру, если возможно равенство монет
![image](https://github.com/user-attachments/assets/d2bdb334-1503-4caf-94b7-06cce4ff2729)
- тут вообще что-то с расчётами, золота ещё много на карте!!! возможно долго не могли затащить монеты на корабль, надо разобраться!
![image](https://github.com/user-attachments/assets/94770a6d-976e-4615-83c6-b1dbad3612bc)
- если карта открыта и есть одна нора, то монеты в этой норе считать потерянными (выбывшими из игры)

P.S. тут дополнение от безумного Макса
1) нужно добавить ф-ции определения терминальных состояний - закончились закрытые клетки, закончились у кого-то пираты, закончились ходы, закончились доступные монеты (не на людоеде) и т.п.
2) при изменении любого из количественных параметров, связанных с клетками, пиратами, ходами, монетами - пересчитывать соот. ф-ции и определять, не наступило ли какое-то терминальное состояние
3) наступление любого терминального состояния инициирует логический вывод - может ли игра быть продолжена
4) только если игра не может быть продолжена - определяется победитель
как-то так

**Comment by madddmax** [comment]
Доработал условия окончания игры:
1. Если вся карта открыта, а у одной команды существенный перевес по золоту и свободное золото на карте не повлияет - то заканчиваем игру. 
2. Заканчиваем игру если все пираты у всех команд почувствовали что не смогут дальше ходить. 
3. Закончилось золото на открытой карте.
4. Яичинг 50*количество игроков ходов, это ходы без переноса золота и открытия новых клеток.
5. Людоед стал монеты есть, т.к. пока нет Пятницы - думаю это приемлемо.
