### ISSUE TITLE
Make move to crocodile from fort

### ISSUE THREAD

**Issue by grmike** [madddmax/jackal#119]
![image](https://github.com/user-attachments/assets/ed692da1-70d6-4874-be92-64d3a7e6555a)
При заходе на крокодила из форта происходит что-то не понятное!
Проверить!

**Comment by madddmax** [comment]
Пофиксили, теперь дается выбор с какой клетки идем на не открытую клетку (на которой может быть лед или крокодил). И в зависимости от выбора обрабатываем переход.
