### ISSUE TITLE
[BugReport] Pirates dead game freeze

### ISSUE THREAD

**Issue by Graf64** [madddmax/jackal#19]
Фактический результат. Если у игрока-человека все пираты погибли, игра остановилась. Отсутствует сообщение об окончании игры.
Ожидаемый результат. Если у игрока-человека все пираты погибли, игра продолжается между компьютерами. По завершению игры появляется сообщение об окончании и победителе.

Аналогичная ситуация возникает, если все попали в яму или нет хода по другим причинами

Код игры: 9133fffa-8c28-4c08-bd17-784630c40f66
Код карты: 2109058948
Номер хода: 632

**Comment by madddmax** [comment]
Готово. Можно проверять.
