### ISSUE TITLE
Generating tiles for different map sizes

### ISSUE THREAD

**Issue by madddmax** [madddmax/jackal#23]
Нужно описать алгоритм из каких игровых клеток генерировать карту различного размера. Изначально был спроектирован алгоритм для стандартной карты состоящей из следующих игровых клеток (название - описание - количество):
Chest1 - сундук 1 монета - 5
Chest2 - сундук 2 монеты - 5
Chest3 - сундук 3 монеты - 3
Chest4 - сундук 4 монеты - 2
Chest5 - сундук 5 монет - 1
Fort - форт - 2
RespawnFort - форт с девушкой - 1
RumBarrel - бочка рома - 4
Horse - лошадь - 2
Balloon - воздушный шар - 2
Airplane - самолет - 1
Croc - крокодил - 4
Ice - лед - 6
Cannon - пушка - 2
Arrow - стрелки 7 видов - 7*3=21
Spinning2 - задерживающие джунгли - 5
Spinning3 - пустыня - 4
Spinning4 - болото - 2
Spinning5 - горы - 1
Trap - яма ловушка - 3
Canibal - людоед - 1
Grass - простое поле - 40
Итого: 77 + 40 = 117 (размер карты 13)

**Comment by Graf64** [comment]
Формула определения количества игровых клеток карты (КИКК).
КИКК = (размер - 2)*(размер - 2) - 4
Получаем КИКК_13 = 11*11 - 4 = 117
КИКК_11 = 9*9 - 4 = 77   77/117 = **66%**
КИКК_9 = 7*7 - 4 = 45     45/117 = **38%**
КИКК_7 = 5*5 - 4 = 21     21/117 = **18%**
КИКК_5 = 3*3 -4 = 5         5/117 = **4%**

**Comment by Graf64** [comment]
Дальше генерацию осуществляем с помощью рандома
вычисляем Chest1count для карты с размером 9
//Получить случайное число (в диапазоне от 0 до 100)
int value = rnd.Next(0, 100)
Процент КИКК (ПКИКК) рассчитан выше.
Например ПКИКК = 38
Chest1countBase = 5 для 100%

Вариант 1
Chest1count = 0; //инициализируем Chest1count для нашей карты размером 9
PercentMap = 38
В цикле 
for (count = 0; count < Chest1countBase; count++)
{
int value = rnd.Next(0, 100)
if (value < PercentMap) Chest1count++;
}
На выходе из цикла получим Chest1count для размера 9
С учетом рандома количество при каждой генерации может отличатся.
Так генерируем все клетки кроме пустых.
Проверяем, что общее количество клеток меньше и равно количеству сгенерированных игровых (кроме пустых)
Дополняем набор пустыми клетками, если необходимо.
Если получилось, что мы сгенерировали больше, чем может вместить игровое поле, тогда это ошибка и требуется повторная генерация без переинициализации рандомайз таймера (чтобы был новый рандом)

**Comment by Graf64** [comment]
Вариант 2
PercenMap = 38

Целочисленно делим
Chest1count = Chest1countBase*100/PercentMap 
В нашем примере получим
Chest1count = 5*100/38 = 13 (ЦЕЛАЯ ЧАСТЬ ОТ 13.1578)
RespawnFortCount = 1*100/38 = 0
CanibalCount =  1*100/38 = 0

И так далее для всех и дополняем пустыми клетками до полного количества игровых клеток для данного размера.

**Comment by madddmax** [comment]
Вариант 2 - выглядит попроще и думаю с него начать. Можно произвести расчет КИИК_5, какие там будут в итоге клетки?

**Comment by madddmax** [comment]
Все устроило, кроме генерации людоеда и форта воскрешения. По ТЗ должны быть вместе.

**Comment by madddmax** [comment]
Готово https://github.com/madddmax/jackal/blob/0a4751372dbd998e68457ff2369e65e5f6b99285/Jackal.Core/MapGenerator/ClassicTilesPack.cs#L15
