### ISSUE TITLE
Некорректные ходы с коня

### ISSUE THREAD

**Issue by grmike** [madddmax/jackal#25]
![image_2024-07-29_11-29-36](https://github.com/user-attachments/assets/8260aab7-6822-489a-aa80-777b3715e9cd)

Если с коня открывается лёд, то предлагается сделать более длинный ход, чем должен быть.
Выглядит, что рассчёт идёт от первоначального положения пирата (на корабле).
Работает не только с конём, но и со стрелкой на лёд
Код карты: 2007093277
Размер карты: 11

![image_2024-08-04_15-46-16](https://github.com/user-attachments/assets/46d0a74d-ee75-49c2-9620-7dfbc2f7583c)

**Comment by madddmax** [comment]
Fix
