### ISSUE TITLE
Имба со льдом

### ISSUE THREAD

**Issue by grmike** [madddmax/jackal#26]
![image_2024-07-29_11-31-11](https://github.com/user-attachments/assets/b70e7613-ddb6-42ae-bc56-0296a73f2a33)

Конь со льдом превращается в имбу.
Хотели это поправить, чтобы с коня на лёд делал возможным только один продолжающий ход

**Comment by Graf64** [comment]
У вас продуман вариант, если лед является береговой клеткой и продолжение хода идет в воду за пределы водной карты?

**Comment by madddmax** [comment]
@Graf64 по поводу выхода за предел карты через коня и лед, такого еще не было. По идее просто в воду попадаем ряжом с берегом. Но это отдельный issue

**Comment by madddmax** [comment]
Fixed
