### ISSUE TITLE
can not move to air balloon with/without coin

### ISSUE THREAD

**Issue by grmike** [madddmax/jackal#3]
map code = 467488989
![image](https://github.com/madddmax/jackal/assets/4492830/23e1abad-0f1b-4e97-8a9d-0b77cc0c7b78)
can not move to air balloon with/without coin

**Comment by madddmax** [comment]
Это не баг, а фича. Сам подумай зачем ставить пирата на воздушный шар, его надо ставить сразу на корабль! Так что это проблема визуализации отображения возможных ходов - не заметен без пристального рассматривания возможный ход на корабль. Предлагаю сделать выделение рамкой или рисовать например зеленые кружки куда можно ходить, посмотреть как в шахматах делают.
