### ISSUE TITLE
Error ICE move

### ISSUE THREAD

**Issue by Graf64** [madddmax/jackal#32]
Ход через лед и стрелку вычисляется некорректно при открытии клетки льда
Код игры: 8fdb7198-3471-4c12-9eb1-bea7224f48e4
Код карты: 2083032020
Размер карты: 11
Номер хода: 8
![изображение](https://github.com/user-attachments/assets/749afcc2-7fab-4b57-9b0a-4ddf0f723f16)

Код игры: 46e936e7-7bdd-4420-9c37-f9fb001a351e
Код карты: -1482251825
Размер карты: 11
Номер хода: 168
![изображение](https://github.com/user-attachments/assets/8db6b463-2330-4a03-8e01-0ddb74ecabf3)

**Comment by madddmax** [comment]
Done
