### ISSUE TITLE
Error lighthouse move

### ISSUE THREAD

**Issue by Graf64** [madddmax/jackal#71]
Маяк открывает 4 клетки.
Но если осталось всего 2 клетки, от игрок их открывает и пират больше не имеет права хода.
Код игры: db2f953c-95e3-4826-b4da-7add16719807
Код карты: 1585514655
Размер карты: 11
Номер хода: 652

**Comment by madddmax** [comment]
Не удалось воспроизвести, будем считать что работает как надо.
